'use strict';

export default {
  UPDATE_DATA: 'UPDATE_DATA',
  TOGGLE_TODO: 'TOGGLE_TODO',
  CLEAR_TODOS: 'CLEAR_TODOS',
  ROUTE_CHANGED: 'ROUTE_CHANGED',
  PAGE_IMAGE_LOADED: 'PAGE_IMAGE_LOADED',
  PAGE_IMAGE_LOADING: 'PAGE_IMAGE_LOADING',
  IMAGE_RECTANGLE_SELECTED: 'IMAGE_RECTANGLE_SELECTED',
  TASK_REQUESTED: 'NEXT_TASK_REQUESTED',
  TASK_LOADED: 'TASK_LOADED',
};
